name: fireeye
description: Akıllı Yangın Uyarı Sistemi
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  flutter_native_splash: ^2.4.6
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/fireeye_icon.png
    - assets/images/  # Diğer resimlerin varsa klasörünü burada tanımla

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/images/fireeye_logo.png
  min_sdk_android: 21

